package cr.ac.una.reservas.presentation.mvc.componentes;

import cr.ac.una.reservas.presentation.mvc.iconos.IconoSemantico;
import cr.ac.una.reservas.presentation.mvc.tema.CambioTemaListener;
import cr.ac.una.reservas.presentation.mvc.tema.GestorTema;
import cr.ac.una.reservas.presentation.mvc.tema.Tema;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class BarraSuperior implements CambioTemaListener {
    private static final int ALTO_BARRA = 28;

    private JPanel BarraSuperior;
    private JPanel btnSalir;

    private BotonIcono botonSalirReal;
    private JPanel envoltorio;
    private Point puntoArrastre;

    public BarraSuperior() {
        $$$setupUI$$$();
        BarraSuperior.setOpaque(false);
        GestorTema.obtenerInstancia().agregarListener(this);
        aplicarTema(GestorTema.obtenerInstancia().temaActivo());
    }

    private void createUIComponents() {
        botonSalirReal = new BotonIcono();
        botonSalirReal.setIcono(IconoSemantico.CERRAR_VENTANA.icono());
        botonSalirReal.setTamano(22, 22);
        btnSalir = botonSalirReal.obtenerPanel();
    }

    public void alCerrar(Runnable accion) {
        botonSalirReal.alHacerClick(accion);
    }

    public JPanel obtenerPanel() {
        if (envoltorio == null) {
            envoltorio = new JPanel(new BorderLayout());
            envoltorio.setOpaque(false);
            envoltorio.setPreferredSize(new Dimension(10, ALTO_BARRA));
            envoltorio.setMinimumSize(new Dimension(10, ALTO_BARRA));
            envoltorio.setMaximumSize(new Dimension(Integer.MAX_VALUE, ALTO_BARRA));
            envoltorio.add(BarraSuperior, BorderLayout.CENTER);
            habilitarArrastreDeVentana(envoltorio);
            habilitarArrastreDeVentana(BarraSuperior);
        }
        return envoltorio;
    }

    private void habilitarArrastreDeVentana(JComponent componente) {
        MouseAdapter arrastre = new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent evento) {
                Window ventana = SwingUtilities.getWindowAncestor(componente);
                if (ventana == null) {
                    puntoArrastre = null;
                    return;
                }
                puntoArrastre = SwingUtilities.convertPoint(componente, evento.getPoint(), ventana);
            }

            @Override
            public void mouseReleased(MouseEvent evento) {
                puntoArrastre = null;
            }

            @Override
            public void mouseDragged(MouseEvent evento) {
                if (puntoArrastre == null) {
                    return;
                }
                Window ventana = SwingUtilities.getWindowAncestor(componente);
                if (ventana == null) {
                    return;
                }
                Point enPantalla = evento.getLocationOnScreen();
                ventana.setLocation(enPantalla.x - puntoArrastre.x, enPantalla.y - puntoArrastre.y);
            }
        };
        componente.addMouseListener(arrastre);
        componente.addMouseMotionListener(arrastre);
    }

    @Override
    public void onCambioTema(Tema tema) {
        aplicarTema(tema);
    }

    private void aplicarTema(Tema tema) {
        BarraSuperior.setOpaque(false);
        BarraSuperior.repaint();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        BarraSuperior = new JPanel();
        BarraSuperior.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(4, 4, 4, 4), 4, -1));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        BarraSuperior.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        BarraSuperior.add(btnSalir, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return BarraSuperior;
    }
}
