package cr.ac.una.reservas.presentation.mvc.componentes;

import cr.ac.una.reservas.presentation.mvc.iconos.Icono;
import cr.ac.una.reservas.presentation.mvc.iconos.IconoAplicador;
import cr.ac.una.reservas.presentation.mvc.tema.CambioTemaListener;
import cr.ac.una.reservas.presentation.mvc.tema.GestorTema;
import cr.ac.una.reservas.presentation.mvc.tema.Tema;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class BotonPrimario implements CambioTemaListener {

    private static final int RADIO_BORDE = 10;

    private JPanel BotonPrimario;
    private JButton btnPrimario;
    private JLabel lblIcon;

    private Color colorBase;
    private Color colorHover;
    private boolean sobreBoton;

    public BotonPrimario() {
        $$$setupUI$$$();
        BotonPrimario.setOpaque(false);
        GestorTema.obtenerInstancia().agregarListener(this);
        aplicarTema(GestorTema.obtenerInstancia().temaActivo());
    }

    private void createUIComponents() {
        btnPrimario = new JButton() {
            @Override
            protected void paintComponent(Graphics graficos) {
                Graphics2D graficos2D = (Graphics2D) graficos.create();
                graficos2D.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                graficos2D.setColor(sobreBoton ? colorHover : colorBase);
                graficos2D.fillRoundRect(0, 0, getWidth(), getHeight(), RADIO_BORDE, RADIO_BORDE);
                graficos2D.dispose();
                super.paintComponent(graficos);
            }
        };
        btnPrimario.setContentAreaFilled(false);
        btnPrimario.setFocusPainted(false);
        btnPrimario.setBorderPainted(false);
        btnPrimario.setBorder(new EmptyBorder(8, 18, 8, 18));
        btnPrimario.setFocusable(false);
        btnPrimario.setOpaque(false);
        btnPrimario.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent evento) {
                sobreBoton = true;
                btnPrimario.repaint();
            }

            @Override
            public void mouseExited(MouseEvent evento) {
                sobreBoton = false;
                btnPrimario.repaint();
            }
        });
    }

    public void setTexto(String texto) {
        btnPrimario.setText(texto);
    }

    public void setIcono(Icono icono) {
        IconoAplicador.aplicar(lblIcon, icono, 13f, GestorTema.obtenerInstancia().temaActivo().colorTexto());
    }

    public void alHacerClick(Runnable accion) {
        btnPrimario.addActionListener(evento -> accion.run());
    }

    public JPanel obtenerPanel() {
        return BotonPrimario;
    }

    @Override
    public void onCambioTema(Tema tema) {
        aplicarTema(tema);
    }

    private void aplicarTema(Tema tema) {
        colorBase = tema.colorPrimario();
        colorHover = tema.colorPrimarioHover();
        btnPrimario.setForeground(tema.colorTexto());
        btnPrimario.setFont(tema.fuenteTexto());
        lblIcon.setForeground(tema.colorTexto());
        btnPrimario.repaint();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        BotonPrimario = new JPanel();
        BotonPrimario.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        btnPrimario.setText("Boton Primario");
        BotonPrimario.add(btnPrimario, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblIcon = new JLabel();
        lblIcon.setText("");
        BotonPrimario.add(lblIcon, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return BotonPrimario;
    }
}
