package cr.ac.una.reservas.presentation.mvc.componentes;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import cr.ac.una.reservas.presentation.mvc.tema.CambioTemaListener;
import cr.ac.una.reservas.presentation.mvc.tema.GestorTema;
import cr.ac.una.reservas.presentation.mvc.tema.Tema;

import javax.swing.*;
import java.awt.*;

public class CeldaMatriz implements CambioTemaListener {
    private static final int RADIO_BORDE = 8;

    private JPanel CeldaMatriz;
    private JLabel lblTextoPrincipal;
    private JLabel lblTextoSecundario;

    private Color colorFondo;

    public CeldaMatriz() {
        $$$setupUI$$$();
        GestorTema.obtenerInstancia().agregarListener(this);
        aplicarTema(GestorTema.obtenerInstancia().temaActivo());
    }

    private void createUIComponents() {
        CeldaMatriz = new JPanel() {
            @Override
            protected void paintComponent(Graphics graficos) {
                Graphics2D graficos2D = (Graphics2D) graficos.create();
                graficos2D.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                graficos2D.setColor(colorFondo);
                graficos2D.fillRoundRect(0, 0, getWidth(), getHeight(), RADIO_BORDE, RADIO_BORDE);
                graficos2D.dispose();
                super.paintComponent(graficos);
            }
        };
        CeldaMatriz.setOpaque(false);
    }

    public void setDatos(DatosCelda datos) {
        lblTextoPrincipal.setText(datos.getTextoPrincipal());
        lblTextoSecundario.setText(datos.getTextoSecundario() == null ? "" : datos.getTextoSecundario());
        colorFondo = datos.getColor();
        CeldaMatriz.repaint();
    }

    public JPanel obtenerPanel() {
        return CeldaMatriz;
    }

    @Override
    public void onCambioTema(Tema tema) {
        aplicarTema(tema);
    }

    private void aplicarTema(Tema tema) {
        if (colorFondo == null) {
            colorFondo = tema.colorPrimario();
        }
        Font fuenteBase = tema.fuenteTexto();
        lblTextoPrincipal.setForeground(tema.colorTexto());
        lblTextoPrincipal.setFont(fuenteBase.deriveFont(Font.BOLD));
        lblTextoSecundario.setForeground(tema.colorTexto());
        lblTextoSecundario.setFont(fuenteBase.deriveFont(fuenteBase.getSize2D() - 1f));
        CeldaMatriz.repaint();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        CeldaMatriz.setLayout(new GridLayoutManager(2, 1, new Insets(4, 6, 4, 6), -1, 2));
        lblTextoPrincipal = new JLabel();
        lblTextoPrincipal.setText("Actividad");
        CeldaMatriz.add(lblTextoPrincipal, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblTextoSecundario = new JLabel();
        lblTextoSecundario.setText("(Detalle)");
        CeldaMatriz.add(lblTextoSecundario, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return CeldaMatriz;
    }

}
