package cr.ac.una.reservas.presentation.mvc.componentes;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import cr.ac.una.reservas.presentation.mvc.iconos.Icono;
import cr.ac.una.reservas.presentation.mvc.iconos.IconoAplicador;
import cr.ac.una.reservas.presentation.mvc.tema.CambioTemaListener;
import cr.ac.una.reservas.presentation.mvc.tema.GestorTema;
import cr.ac.una.reservas.presentation.mvc.tema.Tema;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

public class Popup implements CambioTemaListener {

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlContenidoPopup = new JPanel();
        pnlContenidoPopup.setLayout(new GridLayoutManager(3, 2, new Insets(20, 20, 16, 20), 10, 12));
        lblIconoPopup = new JLabel();
        lblIconoPopup.setText("");
        pnlContenidoPopup.add(lblIconoPopup, new GridConstraints(0, 0, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblTituloPopup = new JLabel();
        lblTituloPopup.setText("Titulo");
        pnlContenidoPopup.add(lblTituloPopup, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblMensajePopup = new JLabel();
        lblMensajePopup.setText("Mensaje");
        pnlContenidoPopup.add(lblMensajePopup, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pnlContenidoPopup.add(pnlBotonesPopup, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_SOUTHEAST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlContenidoPopup;
    }

    public enum Tipo {
        INFORMACION,
        ERROR,
        CONFIRMACION,
        CARGANDO
    }

    public static class AccionPopup {
        private final String texto;
        private final boolean esPrincipal;
        private final Runnable accion;

        public AccionPopup(String texto, boolean esPrincipal, Runnable accion) {
            this.texto = texto;
            this.esPrincipal = esPrincipal;
            this.accion = accion;
        }
    }

    private static final int RADIO_BORDE = 14;

    private JDialog dialogoRaiz;
    private JPanel pnlContenidoPopup;
    private JLabel lblIconoPopup;
    private JLabel lblTituloPopup;
    private JLabel lblMensajePopup;
    private JPanel pnlBotonesPopup;

    private Tipo tipo = Tipo.INFORMACION;

    public Popup(Frame propietario) {
        this(propietario, true);
    }

    public Popup(Frame propietario, boolean modal) {
        $$$setupUI$$$();
        construirDialogo(propietario, modal);
        GestorTema.obtenerInstancia().agregarListener(this);
        aplicarTema(GestorTema.obtenerInstancia().temaActivo());
    }

    private void construirDialogo(Frame propietario, boolean modal) {
        dialogoRaiz = new JDialog(propietario, modal) {
            @Override
            public void paint(Graphics graficos) {
                Graphics2D graficos2D = (Graphics2D) graficos.create();
                graficos2D.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                graficos2D.setColor(getContentPane().getBackground());
                graficos2D.fillRoundRect(0, 0, getWidth(), getHeight(), RADIO_BORDE, RADIO_BORDE);
                graficos2D.dispose();
                super.paint(graficos);
            }
        };
        dialogoRaiz.setUndecorated(true);
        dialogoRaiz.setResizable(false);
        dialogoRaiz.setDefaultCloseOperation(modal ? JDialog.DISPOSE_ON_CLOSE : JDialog.DO_NOTHING_ON_CLOSE);
        dialogoRaiz.setContentPane(pnlContenidoPopup);
    }

    private void createUIComponents() {
        pnlBotonesPopup = new JPanel(new FlowLayout(FlowLayout.RIGHT, 8, 0));
        pnlBotonesPopup.setOpaque(false);
    }

    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
        aplicarTema(GestorTema.obtenerInstancia().temaActivo());
    }

    public void setTitulo(String titulo) {
        lblTituloPopup.setText(titulo);
    }

    public void setMensaje(String mensaje) {
        lblMensajePopup.setText("<html><body style='width: 220px'>" + mensaje + "</body></html>");
    }

    public void setAcciones(List<AccionPopup> acciones) {
        pnlBotonesPopup.removeAll();
        for (AccionPopup accionPopup : acciones) {
            pnlBotonesPopup.add(crearBoton(accionPopup));
        }
        pnlBotonesPopup.revalidate();
        pnlBotonesPopup.repaint();
    }

    private Component crearBoton(AccionPopup accionPopup) {
        Runnable accionConCierre = () -> {
            if (accionPopup.accion != null) {
                accionPopup.accion.run();
            }
            cerrar();
        };
        if (accionPopup.esPrincipal) {
            BotonPrimario boton = new BotonPrimario();
            boton.setTexto(accionPopup.texto);
            boton.alHacerClick(accionConCierre);
            return boton.obtenerPanel();
        }
        BotonSecundario boton = new BotonSecundario();
        boton.setTexto(accionPopup.texto);
        boton.alHacerClick(accionConCierre);
        return boton.obtenerPanel();
    }

    public static void mostrarAviso(Frame propietario, Tipo tipo, String titulo, String mensaje) {
        Popup popup = new Popup(propietario);
        popup.setTipo(tipo);
        popup.setTitulo(titulo);
        popup.setMensaje(mensaje);
        List<AccionPopup> acciones = new ArrayList<>();
        acciones.add(new AccionPopup("Aceptar", true, null));
        popup.setAcciones(acciones);
        popup.mostrar();
    }

    public static Popup mostrarCargando(Frame propietario, String titulo, String mensaje) {
        Popup popup = new Popup(propietario, false);
        popup.setTipo(Tipo.CARGANDO);
        popup.setTitulo(titulo);
        popup.setMensaje(mensaje);
        popup.setAcciones(new ArrayList<>());
        popup.mostrar();
        return popup;
    }

    public void mostrar() {
        dialogoRaiz.pack();
        dialogoRaiz.setLocationRelativeTo(dialogoRaiz.getOwner());
        dialogoRaiz.setVisible(true);
    }

    public void cerrar() {
        dialogoRaiz.dispose();
    }

    @Override
    public void onCambioTema(Tema tema) {
        aplicarTema(tema);
    }

    private void aplicarTema(Tema tema) {
        Color colorIcono = colorSegunTipo(tema);
        Icono icono = iconoSegunTipo();

        dialogoRaiz.getContentPane().setBackground(tema.colorFondoTarjeta());
        IconoAplicador.aplicar(lblIconoPopup, icono, 28f, colorIcono);

        lblTituloPopup.setForeground(tema.colorTexto());
        lblTituloPopup.setFont(tema.fuenteTitulo().deriveFont(15f));

        lblMensajePopup.setForeground(tema.colorTextoSecundario());
        lblMensajePopup.setFont(tema.fuenteTexto());

        dialogoRaiz.repaint();
    }

    private Color colorSegunTipo(Tema tema) {
        return tipo == Tipo.ERROR ? tema.colorPeligro() : tema.colorPrimario();
    }

    private Icono iconoSegunTipo() {
        switch (tipo) {
            case ERROR:
                return Icono.ALERTA;
            case CONFIRMACION:
                return Icono.CHECK;
            case CARGANDO:
                return Icono.NUBE;
            case INFORMACION:
            default:
                return Icono.INFO;
        }
    }
}
