package cr.ac.una.reservas.presentation.mvc.componentes;

import cr.ac.una.reservas.presentation.mvc.iconos.Icono;
import cr.ac.una.reservas.presentation.mvc.iconos.IconoAplicador;
import cr.ac.una.reservas.presentation.mvc.tema.CambioTemaListener;
import cr.ac.una.reservas.presentation.mvc.tema.GestorTema;
import cr.ac.una.reservas.presentation.mvc.tema.Tema;

import javax.swing.*;
import java.awt.*;

public class Tarjeta implements CambioTemaListener {

    private static final int RADIO_BORDE = 16;

    private JPanel PanelTarjeta;
    private JPanel pnlEncabezado;
    private JLabel lblIconoEncabezado;
    private JLabel lblTituloEncabezado;
    private JLabel lblSubtituloEncabezado;
    private JPanel pnlAccionEncabezado;
    private JPanel pnlContenido;

    public Tarjeta() {
        $$$setupUI$$$();
        GestorTema.obtenerInstancia().agregarListener(this);
        pnlEncabezado.setOpaque(false);
        lblTituloEncabezado.setHorizontalAlignment(SwingConstants.LEFT);
        lblSubtituloEncabezado.setHorizontalAlignment(SwingConstants.LEFT);
        lblSubtituloEncabezado.setText("");
        aplicarTema(GestorTema.obtenerInstancia().temaActivo());
        pnlEncabezado.setVisible(false);
    }

    private void createUIComponents() {
        PanelTarjeta = new JPanel() {
            @Override
            protected void paintComponent(Graphics graficos) {
                Graphics2D graficos2D = (Graphics2D) graficos.create();
                graficos2D.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                graficos2D.setColor(getBackground());
                graficos2D.fillRoundRect(0, 0, getWidth(), getHeight(), RADIO_BORDE, RADIO_BORDE);
                graficos2D.dispose();
                super.paintComponent(graficos);
            }
        };
        PanelTarjeta.setOpaque(false);

        pnlAccionEncabezado = new JPanel(new BorderLayout());
        pnlAccionEncabezado.setOpaque(false);

        pnlContenido = new JPanel(new BorderLayout());
        pnlContenido.setOpaque(false);
    }


    public void setTitulo(String titulo) {
        pnlEncabezado.setVisible(true);
        lblTituloEncabezado.setText(titulo);
        lblTituloEncabezado.setHorizontalAlignment(SwingConstants.LEFT);
    }

    public void setSubtitulo(String subtitulo) {
        pnlEncabezado.setVisible(true);
        lblSubtituloEncabezado.setText(subtitulo);
        lblSubtituloEncabezado.setHorizontalAlignment(SwingConstants.LEFT);
    }

    public void setIcono(Icono icono) {
        pnlEncabezado.setVisible(true);
        IconoAplicador.aplicar(lblIconoEncabezado, icono, 17f, GestorTema.obtenerInstancia().temaActivo().colorPrimario());
    }

    public void setAccion(JPanel panelAccion) {
        pnlEncabezado.setVisible(true);
        pnlAccionEncabezado.removeAll();
        pnlAccionEncabezado.add(panelAccion, BorderLayout.CENTER);
        pnlAccionEncabezado.revalidate();
    }

    public JPanel obtenerPanelContenido() {
        return pnlContenido;
    }

    public JPanel obtenerPanel() {
        return PanelTarjeta;
    }

    @Override
    public void onCambioTema(Tema tema) {
        aplicarTema(tema);
    }

    private void aplicarTema(Tema tema) {
        Color fondo = tema.colorFondoTarjeta();
        PanelTarjeta.setBackground(fondo);
        lblTituloEncabezado.setForeground(tema.colorTexto());
        lblTituloEncabezado.setFont(tema.fuenteTitulo().deriveFont(15f));
        lblSubtituloEncabezado.setForeground(tema.colorTextoSecundario());
        lblSubtituloEncabezado.setFont(tema.fuenteTexto().deriveFont(11.5f));
        PanelTarjeta.repaint();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        PanelTarjeta.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(14, 16, 14, 16), -1, 8));
        pnlEncabezado = new JPanel();
        pnlEncabezado.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), 8, 0));
        PanelTarjeta.add(pnlEncabezado, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblIconoEncabezado = new JLabel();
        lblIconoEncabezado.setText("");
        pnlEncabezado.add(lblIconoEncabezado, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblTituloEncabezado = new JLabel();
        lblTituloEncabezado.setText("Titulo");
        pnlEncabezado.add(lblTituloEncabezado, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblSubtituloEncabezado = new JLabel();
        lblSubtituloEncabezado.setText("Subtitulo");
        pnlEncabezado.add(lblSubtituloEncabezado, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pnlEncabezado.add(pnlAccionEncabezado, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHEAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        PanelTarjeta.add(pnlContenido, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return PanelTarjeta;
    }
}
